import * as APIUtil from '../util/session_api_util';

const RECEIVE_SESSION_ERRORS ='RECEIVE_SESSION_ERRORS';
const RECEIVE_CURRENT_USER ='RECEIVE_CURRENT_USER';
const LOGOUT_CURRENT_USER ='LOGOUT_CURRENT_USER';


